### ISSUE TITLE
Add support for arm

### ISSUE THREAD

**Issue by jonringer** [SkylerLipthay/ducc#5]
while compiling for arm, got the following errors:

<details> <summary> build errors </summary>

```
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:117:38
    |
117 |     ffi::duk_get_prop_string(ctx, 0, ERROR_KEY.as_ptr());
    |                                      ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:121:38
    |
121 |     ffi::duk_put_prop_string(ctx, 0, ERROR_KEY.as_ptr());
    |                                      ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:157:43
    |
157 |         ffi::duk_put_prop_string(ctx, -2, ERROR_KEY.as_ptr());
    |                                           ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:167:43
    |
167 |         ffi::duk_get_prop_string(ctx, -1, ERROR_KEY.as_ptr());
    |                                           ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:171:43
    |
171 |         ffi::duk_put_prop_string(ctx, -2, ERROR_KEY.as_ptr());
    |                                           ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:260:37
    |
260 |     ffi::duk_put_global_string(ctx, UDATA.as_ptr());
    |                                     ^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:264:37
    |
264 |     ffi::duk_put_global_string(ctx, ANYMAP.as_ptr());
    |                                     ^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:276:37
    |
276 |     ffi::duk_get_global_string(ctx, UDATA.as_ptr());
    |                                     ^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/util.rs:283:37
    |
283 |     ffi::duk_get_global_string(ctx, ANYMAP.as_ptr());
    |                                     ^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/ducc.rs:367:50
    |
367 |             ffi::duk_get_global_string(self.ctx, STASH_KEY.as_ptr());
    |                                                  ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/ducc.rs:390:50
    |
390 |             ffi::duk_put_global_string(self.ctx, STASH_KEY.as_ptr());
    |                                                  ^^^^^^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/function.rs:130:52
    |
130 |             ffi::duk_put_prop_string(ducc.ctx, -2, FUNC.as_ptr());
    |                                                    ^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
  --> /build/texlab-1.7.0-vendor/ducc/src/function.rs:86:47
   |
86 |             ffi::duk_get_prop_string(ctx, -1, FUNC.as_ptr());
   |                                               ^^^^^^^^^^^^^ expected u8, found i8
   |
   = note: expected type `*const u8`
              found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/function.rs:117:42
    |
117 |         ffi::duk_get_prop_string(ctx, 0, FUNC.as_ptr());
    |                                          ^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error[E0308]: mismatched types
   --> /build/texlab-1.7.0-vendor/ducc/src/function.rs:121:42
    |
121 |         ffi::duk_put_prop_string(ctx, 0, FUNC.as_ptr());
    |                                          ^^^^^^^^^^^^^ expected u8, found i8
    |
    = note: expected type `*const u8`
               found type `*const i8`
error: aborting due to 15 previous errors
For more information about this error, 
```
</details>

full log: https://logs.nix.ci/?key=nixos/nixpkgs.73839&attempt_id=c7ed5679-f27e-4199-adbd-cb2100515246

**Comment by adumbidiot** [comment]
I think that's due to the fact that those functions take in a `c_char`. This is a type alias for either `u8` or `i8` depending on the platform. The code seems to assume that a `c_char` is always a `u8`, not an `i8`. Since these are only pointers, I think this count be easily fixed by doing replacing `<var>.as_ptr()` with something like `<var>.as_ptr() as *const _`.

**Comment by SkylerLipthay** [comment]
A bit late here... But `ducc 0.1.3` has been published with the above PR merged. I don't target ARM myself and I can't verify the build, so follow up if anything is still failing! Thanks!
